# 前端服务配置（管理端 + 用户端 + Nginx）
services:
  # Nginx 网关容器
  nginx-gateway:
    image: nginx:alpine
    container_name: sidifensen-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
      - ./certbot-webroot:/var/www/certbot:ro
    depends_on:
      - frontend-admin
      - frontend-user
    networks:
      - sidifensen-network

  # 前端管理端
  frontend-admin:
    build:
      context: ${PROJECT_ROOT}/sidifensen_blog_frontend/sidifensen_admin
      dockerfile: Dockerfile
    image: sidifensen-blog-admin
    container_name: sidifensen-admin
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT}:80"
    networks:
      - sidifensen-network

  # 前端用户端
  frontend-user:
    build:
      context: ${PROJECT_ROOT}/sidifensen_blog_frontend/sidifensen_user
      dockerfile: Dockerfile
    image: sidifensen-blog-user
    container_name: sidifensen-user
    restart: unless-stopped
    ports:
      - "${USER_PORT}:80"
    networks:
      - sidifensen-network

# 网络
networks:
  sidifensen-network:
    driver: bridge
    name: sidifensen-blog-network
