server:
  port: 5050
spring:
  security:
    jwt:
      secret: sidifensen # jwt 密钥
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sidifensen_blog
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10s
  mail:
    host: smtp.qq.com
    port: 465
    username: 1848221808@qq.com
    password: bwiqwjjrztvxdfie
    properties:
      mail:
        smtp:
          auth: true # 开启SMTP认证
          starttls:
            enable: true # 开启TLS协议
            required: true # 要求使用TLS协议
          ssl:
            enable: true # 开启SSL协议
#        debug: true # 调试模式
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true #是否开启消费者重试
          max-attempts: 3 #最大重试次数
          initial-interval: 6000 #重试间隔时间（单位毫秒）
          multiplier: 2 #间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
          max-interval: 10000 #重试最大时间间隔（单位毫秒）