# 开发环境覆盖配置
version: '3.8'

services:
  # 开发环境下的后端服务配置
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      # 挂载日志目录，方便查看日志
      - ../logs:/app/logs
      # 挂载配置文件，方便修改配置
      - ../sidifensen_blog_backend/src/main/resources:/app/config
    # 开发环境可以暴露调试端口
    ports:
      - "5000:5000"
      - "5005:5005"  # 调试端口

  # 开发环境下的前端服务配置
  frontend-admin:
    volumes:
      # 挂载源码目录，支持热重载
      - ../sidifensen_blog_frontend/sidifensen_admin/src:/app/src
      - ../sidifensen_blog_frontend/sidifensen_admin/public:/app/public
    environment:
      - NODE_ENV=development

  frontend-user:
    volumes:
      # 挂载源码目录，支持热重载
      - ../sidifensen_blog_frontend/sidifensen_user/src:/app/src
      - ../sidifensen_blog_frontend/sidifensen_user/public:/app/public
    environment:
      - NODE_ENV=development


